blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¬ è³ªå•ãƒ»è­°è«–"
    url: "https://github.com/M0G3K0/pokemon-type-chart-quiz/discussions"
    about: "ãƒã‚°ã‚„æ©Ÿèƒ½ææ¡ˆä»¥å¤–ã®ã€ä¸€èˆ¬çš„ãªè³ªå•ã‚„è­°è«–ã¯ã“ã¡ã‚‰ã§è¡Œã£ã¦ãã ã•ã„ã€‚"
